<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class ResultUnifiedVehicleSerializer extends JsonResource
{
    public function toArray($request)
    {
        return [
            'indexVehicle' => $this->indexVehicle,
            'plateVehicle' => $this->plateVehicle,
            'CRVNumber' => $this->CRVNumber,
            'manufactureYear' => $this->manufactureYear,
            'licensingYear' => $this->licensingYear,
            'modelYear' => $this->modelYear,
            'gearBox' => $this->gearBox,
            'weightCapacity' => $this->weightCapacity,
            'passengerCapacity' => $this->passengerCapacity,
            'chassi' => $this->chassi,
            'cylinderCapacity' => $this->cylinderCapacity,
            'cmt' => $this->cmt,
            'fuel' => $this->fuel,
            'color' => $this->color,
            'transferDate' => $this->transferDate,
            'licensingDate' => $this->licensingDate,
            'lesseDocument' => $this->lesseDocument,
            'ownerDocument' => $this->ownerDocument,
            'securityDocument' => $this->securityDocument,
            'validationDocument' => $this->validationDocument,
            'vehicleSpecie' => $this->vehicleSpecie,
            'noticeOfSale' => $this->noticeOfSale,
            'trafficTicketRestriction' => $this->trafficTicketRestriction,
            'recallRestriction' => $this->recallRestriction,
            'renajudRestriction' => $this->renajudRestriction,
            'brandModel' => $this->brandModel,
            'mouting' => $this->mouting,
            'motor' => $this->motor,
            'county' => $this->county,
            'previousCounty' => $this->previousCounty,
            'lesseeName' => $this->lesseeName,
            'ownerName' => $this->ownerName,
            'bodyNumber' => $this->bodyNumber,
            'axisNumber' => $this->axisNumber,
            'auxAxixNumber' => $this->auxAxixNumber,
            'grossTotalWeight' => $this->grossTotalWeight,
            'vehiclePlate' => $this->vehiclePlate,
            'previousVehiclePlate' => $this->previousVehiclePlate,
            'pontecy' => $this->pontecy,
            'origin' => $this->origin,
            'chassisMarkup' => $this->chassisMarkup,
            'renavam' => $this->renavam,
            'restriction' => $this->restriction,
            'licensingStatus' => $this->licensingStatus,
            'situation' => $this->situation,
            'vehicleType' => $this->vehicleType,
            'uf' => $this->uf,
            'previousUf' => $this->previousUf,
            'restriction1' => $this->restriction1,
            'restriction2' => $this->restriction2,
            'restriction3' => $this->restriction3,
            'restriction4' => $this->restriction4,
            'restriction5' => $this->restriction5,
            'validationStatusOwner' => $this->validationStatusOwner,
            'validationStatusRenavam' => $this->validationStatusRenavam,
            'validationStatusUf' => $this->validationStatusUf,
            'validationStatusDocumentImage' => $this->validationStatusDocumentImage,
            'validationStatusChassi' => $this->validationStatusChassi,
            'statusVehicleImage' => $this->statusVehicleImage,
            'statusMessageVehicleImage' => $this->statusMessageVehicleImage,
            'base64VehicleImage' => $this->base64VehicleImage,
            'occurrenceDetail' => isset($this->occurrenceDetail) ? new OccurrenceDetailSerializer($this->occurrenceDetail) : null,
            'infractionDetail' => isset($this->infractionDetail) ? new InfractionDetailSerializer($this->infractionDetail) : null,
            'renajudDetail' => isset($this->renajudDetail) ? new RenajudRestrictionDetailSerializer($this->renajudDetail) : null,
            'anttResponse' => isset($this->anttResponse) ? new AnttResponseSerializer($this->anttResponse) : null,
            'specialAnalysis' => isset($this->specialAnalysis) ? new SpecialAnalysisSerializer($this->specialAnalysis) : null,
        ];
    }

    public static function fromArray(array $data)
    {
        return new static((object) [
            'indexVehicle' => $data['indexVehicle'] ?? null,
            'plateVehicle' => $data['plateVehicle'] ?? null,
            'CRVNumber' => $data['CRVNumber'] ?? null,
            'manufactureYear' => $data['manufactureYear'] ?? null,
            'licensingYear' => $data['licensingYear'] ?? null,
            'modelYear' => $data['modelYear'] ?? null,
            'gearBox' => $data['gearBox'] ?? null,
            'weightCapacity' => $data['weightCapacity'] ?? null,
            'passengerCapacity' => $data['passengerCapacity'] ?? null,
            'chassi' => $data['chassi'] ?? null,
            'cylinderCapacity' => $data['cylinderCapacity'] ?? null,
            'cmt' => $data['cmt'] ?? null,
            'fuel' => $data['fuel'] ?? null,
            'color' => $data['color'] ?? null,
            'transferDate' => $data['transferDate'] ?? null,
            'licensingDate' => $data['licensingDate'] ?? null,
            'lesseDocument' => $data['lesseDocument'] ?? null,
            'ownerDocument' => $data['ownerDocument'] ?? null,
            'securityDocument' => $data['securityDocument'] ?? null,
            'validationDocument' => $data['validationDocument'] ?? null,
            'vehicleSpecie' => $data['vehicleSpecie'] ?? null,
            'noticeOfSale' => $data['noticeOfSale'] ?? null,
            'trafficTicketRestriction' => $data['trafficTicketRestriction'] ?? null,
            'recallRestriction' => $data['recallRestriction'] ?? null,
            'renajudRestriction' => $data['renajudRestriction'] ?? null,
            'brandModel' => $data['brandModel'] ?? null,
            'mouting' => $data['mouting'] ?? null,
            'motor' => $data['motor'] ?? null,
            'county' => $data['county'] ?? null,
            'previousCounty' => $data['previousCounty'] ?? null,
            'lesseeName' => $data['lesseeName'] ?? null,
            'ownerName' => $data['ownerName'] ?? null,
            'bodyNumber' => $data['bodyNumber'] ?? null,
            'axisNumber' => $data['axisNumber'] ?? null,
            'auxAxixNumber' => $data['auxAxixNumber'] ?? null,
            'grossTotalWeight' => $data['grossTotalWeight'] ?? null,
            'vehiclePlate' => $data['vehiclePlate'] ?? null,
            'previousVehiclePlate' => $data['previousVehiclePlate'] ?? null,
            'pontecy' => $data['pontecy'] ?? null,
            'origin' => $data['origin'] ?? null,
            'chassisMarkup' => $data['chassisMarkup'] ?? null,
            'renavam' => $data['renavam'] ?? null,
            'restriction' => $data['restriction'] ?? null,
            'licensingStatus' => $data['licensingStatus'] ?? null,
            'situation' => $data['situation'] ?? null,
            'vehicleType' => $data['vehicleType'] ?? null,
            'uf' => $data['uf'] ?? null,
            'previousUf' => $data['previousUf'] ?? null,
            'restriction1' => $data['restriction1'] ?? null,
            'restriction2' => $data['restriction2'] ?? null,
            'restriction3' => $data['restriction3'] ?? null,
            'restriction4' => $data['restriction4'] ?? null,
            'restriction5' => $data['restriction5'] ?? null,
            'validationStatusOwner' => $data['validationStatusOwner'] ?? null,
            'validationStatusRenavam' => $data['validationStatusRenavam'] ?? null,
            'validationStatusUf' => $data['validationStatusUf'] ?? null,
            'validationStatusDocumentImage' => $data['validationStatusDocumentImage'] ?? null,
            'validationStatusChassi' => $data['validationStatusChassi'] ?? null,
            'statusVehicleImage' => $data['statusVehicleImage'] ?? null,
            'statusMessageVehicleImage' => $data['statusMessageVehicleImage'] ?? null,
            'base64VehicleImage' => $data['base64VehicleImage'] ?? null,
            'occurrenceDetail' => isset($data['occurrenceDetail']) ? OccurrenceDetailSerializer::fromArray($data['occurrenceDetail']) : null,
            'infractionDetail' => isset($data['infractionDetail']) ? InfractionDetailSerializer::fromArray($data['infractionDetail']) : null,
            'renajudDetail' => isset($data['renajudDetail']) ? RenajudRestrictionDetailSerializer::fromArray($data['renajudDetail']) : null,
            'anttResponse' => isset($data['anttResponse']) ? AnttResponseSerializer::fromArray($data['anttResponse']) : null,
            'specialAnalysis' => isset($data['specialAnalysis']) ? SpecialAnalysisSerializer::fromArray($data['specialAnalysis']) : null,
        ]);
    }
}
